### ISSUE TITLE
Add support for unwrapping the SessionFactory from the EntityManagerFactory and decorate the JPA EntityManagerFactory when using JBoss 5 and JPA 1.0

### ISSUE THREAD

**Issue by areus-fundaciobit** [vladmihalcea/hypersistence-optimizer#97]
Trying to install HypersistenceOptimizer 2.1.0-trial on a legacy app on a JBoss EAP 5.2 (Java EE 5 / JPA 1.0 / Hibernate 3.3.2) with JDK 1.7, I try the step 6, "Java EE configuration", on an eagerly initiated servlet I put:

    @PersistenceUnit
    private EntityManagerFactory entityManagerFactory;
    
    private HypersistenceOptimizer hypersistenceOptimizer;

    @Override
    public void init(ServletConfig config) throws ServletException {

        hypersistenceOptimizer = new HypersistenceOptimizer(
            new JpaConfig(
                entityManagerFactory
            )
        );
        ....

On startup, I get to see the big letter logs of HypersistenceOptimizer but then shows this error log:
```

08:46:04,425 ERROR [Hypersistence Optimizer] The [io.hypersistence.optimizer.util.ReflectionUtils] encountered a problem when calling the [handleException] method.
java.lang.IllegalArgumentException: java.lang.reflect.InvocationTargetException
        at io.hypersistence.optimizer.util.ReflectionUtils.handleException(ReflectionUtils.java:781)
        at io.hypersistence.optimizer.util.ReflectionUtils.newInstance(ReflectionUtils.java:153)
        at io.hypersistence.optimizer.util.ReflectionUtils.newInstance(ReflectionUtils.java:128)
        at io.hypersistence.optimizer.util.ReflectionUtils.newInstance(ReflectionUtils.java:73)
        at io.hypersistence.optimizer.core.service.DefaultService.getScanners(DefaultService.java:62)
        at io.hypersistence.optimizer.HypersistenceOptimizer.<init>(HypersistenceOptimizer.java:68)
        at xxxxxxxxx.InitServlet.init(InitServlet.java:61)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1048)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:950)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4122)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4417)
        at org.jboss.web.tomcat.service.deployers.TomcatDeployment.performDeployInternal(TomcatDeployment.java:313)
        at org.jboss.web.tomcat.service.deployers.TomcatDeployment.performDeploy(TomcatDeployment.java:145)
        at org.jboss.web.deployers.AbstractWarDeployment.start(AbstractWarDeployment.java:461)
        at org.jboss.web.deployers.WebModule.startModule(WebModule.java:122)
        at org.jboss.web.deployers.WebModule.start(WebModule.java:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157)
        at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96)
        at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
        at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
        at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:668)
        at org.jboss.system.microcontainer.ServiceProxy.invoke(ServiceProxy.java:206)
        at com.sun.proxy.$Proxy39.start(Unknown Source)
        at org.jboss.system.microcontainer.StartStopLifecycleAction.installAction(StartStopLifecycleAction.java:42)
        at org.jboss.system.microcontainer.StartStopLifecycleAction.installAction(StartStopLifecycleAction.java:37)
        at org.jboss.dependency.plugins.action.SimpleControllerContextAction.simpleInstallAction(SimpleControllerContextAction.java:62)
        at org.jboss.dependency.plugins.action.AccessControllerContextAction.install(AccessControllerContextAction.java:71)
        at org.jboss.dependency.plugins.AbstractControllerContextActions.install(AbstractControllerContextActions.java:51)
        at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
        at org.jboss.system.microcontainer.ServiceControllerContext.install(ServiceControllerContext.java:297)
        at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1652)
        at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:938)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1082)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:988)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:826)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:556)
        at org.jboss.system.ServiceController.doChange(ServiceController.java:688)
        at org.jboss.system.ServiceController.start(ServiceController.java:460)
        at org.jboss.system.deployers.ServiceDeployer.start(ServiceDeployer.java:163)
        at org.jboss.system.deployers.ServiceDeployer.deploy(ServiceDeployer.java:99)
        at org.jboss.system.deployers.ServiceDeployer.deploy(ServiceDeployer.java:46)
        at org.jboss.deployers.spi.deployer.helpers.AbstractSimpleRealDeployer.internalDeploy(AbstractSimpleRealDeployer.java:62)
        at org.jboss.deployers.spi.deployer.helpers.AbstractRealDeployer.deploy(AbstractRealDeployer.java:55)
        at org.jboss.deployers.plugins.deployers.DeployerWrapper.deploy(DeployerWrapper.java:179)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.doDeploy(DeployersImpl.java:1454)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.doInstallParentFirst(DeployersImpl.java:1172)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.doInstallParentFirst(DeployersImpl.java:1193)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.doInstallParentFirst(DeployersImpl.java:1225)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.install(DeployersImpl.java:1113)
        at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
        at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1652)
        at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:938)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1082)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:988)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:826)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:556)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.process(DeployersImpl.java:789)
        at org.jboss.deployers.plugins.main.MainDeployerImpl.process(MainDeployerImpl.java:699)
        at org.jboss.system.server.profileservice.repository.MainDeployerAdapter.process(MainDeployerAdapter.java:117)
        at org.jboss.system.server.profileservice.repository.ProfileDeployAction.install(ProfileDeployAction.java:70)
        at org.jboss.system.server.profileservice.repository.AbstractProfileAction.install(AbstractProfileAction.java:53)
        at org.jboss.system.server.profileservice.repository.AbstractProfileService.install(AbstractProfileService.java:403)
        at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
        at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1652)
        at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:938)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1082)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:988)
        at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:778)
        at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:543)
        at org.jboss.system.server.profileservice.repository.AbstractProfileService.registerProfile(AbstractProfileService.java:308)
        at org.jboss.system.server.profileservice.ProfileServiceBootstrap.start(ProfileServiceBootstrap.java:256)
        at org.jboss.bootstrap.AbstractServerImpl.start(AbstractServerImpl.java:461)
        at org.jboss.Main.boot(Main.java:229)
        at org.jboss.Main$1.call(Main.java:561)
        at org.jboss.Main$1.call(Main.java:557)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at io.hypersistence.optimizer.util.ReflectionUtils.newInstance(ReflectionUtils.java:145)
        ... 79 more
Caused by: java.lang.IllegalArgumentException: The provided EntityManagerFactory [org.jboss.jpa.injection.InjectedEntityManagerFactory@6fb0e5a3] does not implement the org.hibernate.ejb.HibernateEntityManagerFactory class!
        at io.hypersistence.optimizer.hibernate.scanner.AbstractHibernate33Scanner.getSessionFactory(AbstractHibernate33Scanner.java:66)
        at io.hypersistence.optimizer.hibernate.scanner.AbstractHibernate33Scanner.getSessionFactory(AbstractHibernate33Scanner.java:40)
        at io.hypersistence.optimizer.hibernate.scanner.AbstractHibernateScanner.getSessionFactory(AbstractHibernateScanner.java:81)
        at io.hypersistence.optimizer.hibernate.scanner.AbstractHibernate33Scanner.getSessionFactory(AbstractHibernate33Scanner.java:75)
        at io.hypersistence.optimizer.hibernate.scanner.AbstractHibernate33Scanner.<init>(AbstractHibernate33Scanner.java:49)
        at io.hypersistence.optimizer.hibernate.scanner.Hibernate33MappingScanner.<init>(Hibernate33MappingScanner.java:80)
        ... 84 more
08:46:04,439 INFO  [Hypersistence Optimizer] Congratulations! No issue was found.
```

**Comment by vladmihalcea** [comment]
Thanks for reporting the issue.

**Comment by areus-fundaciobit** [comment]
Just tried with another environment that the app works on: JBoss 5.1.0 GA (Java EE 5 / JPA 1.0 / Hibernate 3.3.1 ) with JDK 1.6

But, when the hypersistence optimizer JAR is present inside the library directory of the EAR it fails to deploy with this error:
```

org.jboss.deployers.spi.DeploymentException: Error deploying xxxxx.ear: invalid constant type: 18
        at org.jboss.ejb3.deployers.Ejb3Deployer.deploy(Ejb3Deployer.java:196)
        at org.jboss.ejb3.deployers.Ejb3Deployer.deploy(Ejb3Deployer.java:99)
        at org.jboss.deployers.vfs.spi.deployer.AbstractVFSRealDeployer.internalDeploy(AbstractVFSRealDeployer.java:45)
        at org.jboss.deployers.spi.deployer.helpers.AbstractRealDeployer.deploy(AbstractRealDeployer.java:50)
        at org.jboss.deployers.plugins.deployers.DeployerWrapper.deploy(DeployerWrapper.java:171)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.doDeploy(DeployersImpl.java:1439)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.doInstallParentFirst(DeployersImpl.java:1157)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.install(DeployersImpl.java:1098)
        at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
        at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1631)
        at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:934)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1082)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:984)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:822)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:553)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.process(DeployersImpl.java:781)
        at org.jboss.deployers.plugins.main.MainDeployerImpl.process(MainDeployerImpl.java:702)
        at org.jboss.system.server.profileservice.repository.MainDeployerAdapter.process(MainDeployerAdapter.java:117)
        at org.jboss.system.server.profileservice.repository.ProfileDeployAction.install(ProfileDeployAction.java:70)
        at org.jboss.system.server.profileservice.repository.AbstractProfileAction.install(AbstractProfileAction.java:53)
        at org.jboss.system.server.profileservice.repository.AbstractProfileService.install(AbstractProfileService.java:361)
        at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
        at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1631)
        at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:934)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1082)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:984)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:822)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:553)
        at org.jboss.system.server.profileservice.repository.AbstractProfileService.activateProfile(AbstractProfileService.java:306)
        at org.jboss.system.server.profileservice.ProfileServiceBootstrap.start(ProfileServiceBootstrap.java:271)
        at org.jboss.bootstrap.AbstractServerImpl.start(AbstractServerImpl.java:461)
        at org.jboss.Main.boot(Main.java:221)
        at org.jboss.Main$1.run(Main.java:556)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.io.IOException: invalid constant type: 18
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1027)
        at javassist.bytecode.ConstPool.read(ConstPool.java:970)
        at javassist.bytecode.ConstPool.<init>(ConstPool.java:127)
        at javassist.bytecode.ClassFile.read(ClassFile.java:693)
        at javassist.bytecode.ClassFile.<init>(ClassFile.java:85)
        at org.jboss.ejb3.Ejb3Deployment.deployElement(Ejb3Deployment.java:677)
        at org.jboss.ejb3.Ejb3Deployment.deployUrl(Ejb3Deployment.java:667)
        at org.jboss.ejb3.Ejb3Deployment.deploy(Ejb3Deployment.java:630)
        at org.jboss.ejb3.Ejb3Deployment.create(Ejb3Deployment.java:507)
        at org.jboss.ejb3.deployers.Ejb3Deployer.deploy(Ejb3Deployer.java:182)
        ... 33 more
```

**Comment by vladmihalcea** [comment]
The classes that are needed by Hibernate 3.x are compiled with Java 1.6. In this case, I'm not sure what the JBoss `ClassLoader` tries to load that it's causing this second issue.

Th first issue is easier to fix, the second one might be more complicated. I'll try to set up a JBoss 5 example to see if I can replicate it.

**Comment by vladmihalcea** [comment]
@areus-fundaciobit As a workaround, try to do the following.

Open the `hypersistence-optimizer-2.1.0-trial.jar` and locate the following folders:

- `hypersistence-optimizer-2.1.0-trial.jar\io\hypersistence\optimizer\hibernate\decorator\`
- `hypersistence-optimizer-2.1.0-trial.jar\io\hypersistence\optimizer\hibernate\scanner\`

Remove all classes that have 51, 52, 53, and 54 in their name. Those are compiled with Java 8. 

Let's see if it works.

**Comment by areus-fundaciobit** [comment]
Yes. With this workaround I can deploy the EAR on JBoss 5.1.0 GA. But fails with the same error as with JBoss EAP 5.2.0 when instantiating HypersistenceOptimizer

```
Caused by: java.lang.IllegalArgumentException: The provided EntityManagerFactory [org.jboss.jpa.injection.InjectedEntityManagerFactory@1749c7ac] does not implement the org.hibernate.ejb.HibernateEntityManagerFactory class!
        at io.hypersistence.optimizer.hibernate.scanner.AbstractHibernate33Scanner.getSessionFactory(AbstractHibernate33Scanner.java:66)
        at io.hypersistence.optimizer.hibernate.scanner.AbstractHibernate33Scanner.getSessionFactory(AbstractHibernate33Scanner.java:40)
        at io.hypersistence.optimizer.hibernate.scanner.AbstractHibernateScanner.getSessionFactory(AbstractHibernateScanner.java:81)
        at io.hypersistence.optimizer.hibernate.scanner.AbstractHibernate33Scanner.getSessionFactory(AbstractHibernate33Scanner.java:75)
        at io.hypersistence.optimizer.hibernate.scanner.AbstractHibernate33Scanner.<init>(AbstractHibernate33Scanner.java:49)
        at io.hypersistence.optimizer.hibernate.scanner.Hibernate33MappingScanner.<init>(Hibernate33MappingScanner.java:80)
        ... 82 more
```

**Comment by areus-fundaciobit** [comment]
I managed to get it working. Adding the org.jboss.jpa:jboss-jpa-deployers:1.0.0 to my project, i can cast the injected `EntityManagerFactory` to a `org.jboss.jpa.injection.InjectedEntityManagerFactory` that provides a convenient `getDelegate()` method:

    hypersistenceOptimizer = new HypersistenceOptimizer(
            new JpaConfig(
                    ((InjectedEntityManagerFactory) entityManagerFactory).getDelegate()
            )
    );

Works with both JBoss EAP 5.2.0 over JDK 1.7, and JBoss 5.1.0 GA over JDK 1.6 (with the modified JAR without the Java 8 compiled classes)

**Comment by vladmihalcea** [comment]
Great. Thanks for letting me know.

**Comment by vladmihalcea** [comment]
@areus-fundaciobit I installed JBoss 5 and built a sample JavaEE 5 application and replicated both issues. I'll fix them and release 2.1.1 when I'm done.

**Comment by areus-fundaciobit** [comment]
I just encountered another problem with JBoss 5 when adding the Hypersistence decorator. When I set the provider to `io.hypersistence.optimizer.hibernate.decorator.HypersistenceHibernatePersistenceProvider` on persistence.xml seems that JBoss is unable to create an entity manager factory. Should I post the deatils on this issue or create another one?

**Comment by vladmihalcea** [comment]
@areus-fundaciobit I'm going to test that as well. Most likely, all these issues are caused by the way JBoss wraps the JPA and Hibernate classes.

**Comment by areus-fundaciobit** [comment]
Thats the log I get when JBoss inits the persistence unit, aparently no errors:

```
08:29:45,418 INFO  [PersistenceUnitDeployment] Starting persistence unit persistence.unit:unitName=xxxxx.ear/lib/xxxxxx.jar#xxxxDB
08:29:45,531 INFO  [Version] Hibernate Annotations 3.4.0.GA_CP05
08:29:45,553 INFO  [Environment] Hibernate 3.3.2.GA_CP05
08:29:45,563 INFO  [Environment] hibernate.properties not found
08:29:45,574 INFO  [Environment] Bytecode provider name : javassist
08:29:45,587 INFO  [Environment] using JDK 1.4 java.sql.Timestamp handling
08:29:45,767 INFO  [Version] Hibernate Commons Annotations 3.1.0.GA
08:29:45,774 INFO  [Version] Hibernate EntityManager 3.4.0.GA_CP05
08:29:45,817 INFO  [Ejb3Configuration] Processing PersistenceUnitInfo [
        name: xxxxDB
        ...]
08:29:45,820 INFO  [Ejb3Configuration] Required a different provider: io.hypersistence.optimizer.hibernate.decorator.HypersistenceHibernatePersistenceProvider
```

Whenever an operation requires the `entityManager` I get this error:

```
Caused by: java.lang.NullPointerException
        at org.jboss.jpa.deployment.ManagedEntityManagerFactory.createEntityManager(ManagedEntityManagerFactory.java:195)
        at org.jboss.jpa.deployment.ManagedEntityManagerFactory.getTransactionScopedEntityManager(ManagedEntityManagerFactory.java:174)
        at org.jboss.jpa.tx.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:261)
        at org.jboss.jpa.tx.TransactionScopedEntityManager.createQuery(TransactionScopedEntityManager.java:137)

```

**Comment by vladmihalcea** [comment]
Yes, I know about the issue. It's because JBoss uses a different way of creating the `EntityManager` than the other Java EE application server. I'll take care of that issue as well.

**Comment by vladmihalcea** [comment]
@areus-fundaciobit The fix is going great so far. I only have to create a separate assembly for Java 6 only. Once I'm done with the fix, I will have to run it through a series of tests I have and will release it as 2.1.1. I'll let you know once I publish the fix. Thanks for letting me know it didn't work with JBoss 5. I was previously testing it with Wildfly and Glassfish.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by vladmihalcea** [comment]
@areus-fundaciobit I also create #98 to take care of the Java 8 class enhancement issue you also mentioned.

**Comment by vladmihalcea** [comment]
@areus-fundaciobit Both #97 and #98 have been fixed and included in 2.1.1, which was released. 

First, check out the new [`jre6` dependency](https://vladmihalcea.com/hypersistence-optimizer/docs/installation-guide/#add-dependency-jre-pre-8) which you will need to use when using Java 6 or 7 with JBoss.

The other issues related to resolving the `SessionFactory` and the `EntityManagerFactory` were also fixed and don't require any change on your side.

**Comment by areus-fundaciobit** [comment]
Great!
