### ISSUE TITLE
Spring Boot 3.0.0 dependency 

### ISSUE THREAD

**Issue by tzenker-tzc-itexperts** [vladmihalcea/hypersistence-optimizer#187]
Hypersistence optimizer 2.6.3 config working fine with Spring Boot 2.7.5.

But it throws an error with Spring Boot 3.0.0 when switching from `javax` to `jakarta`.

Hint welcome.

error:

```
.../system/HypersistenceConfiguration.java:30: error: cannot access EntityManagerFactory
                new JpaConfig(entityManagerFactory).setProperties(properties)
                ^
```

Code Snippet:

```
import io.hypersistence.optimizer.HypersistenceOptimizer;
import io.hypersistence.optimizer.core.config.Config;
import io.hypersistence.optimizer.core.config.JpaConfig;
import jakarta.persistence.EntityManagerFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import java.util.HashMap;
import java.util.Map;

@Configuration
public class HypersistenceConfiguration {
    @Bean
    public HypersistenceOptimizer hypersistenceOptimizer(
            EntityManagerFactory entityManagerFactory) {

        Map<String, Object> properties = new HashMap<>();
        properties.put(Config.Property.Session.TIMEOUT_MILLIS, 4500);
        properties.put(Config.Property.Session.FLUSH_TIMEOUT_MILLIS, 800);
        properties.put(Config.Property.Query.MAX_RESULT_SIZE,3000);
        properties.put(Config.Property.Query.TIMEOUT_MILLIS,3000);


        return new HypersistenceOptimizer(
                new JpaConfig(entityManagerFactory).setProperties(properties)
        );
    }
}
```

**Comment by vladmihalcea** [comment]
For Spring Boot 3 and Spring 6, you need to use a different dependency as indicated by the [Installation Guide](https://vladmihalcea.com/hypersistence-optimizer/docs/installation-guide/#Jakarta_Persistence).

````xml
<dependency>
    <groupId>io.hypersistence</groupId>
    <artifactId>hypersistence-optimizer</artifactId>
    <version>2.6.3-jakarta</version>
</dependency>
````
